<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Password change' => 'Зміна паролю',
    'Wrong current password.' => 'Невірний поточний пароль.',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
    'Account details have been updated' => 'Деталі аккаунту оновлені',
    'Active' => 'Активний',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей елемент?',
    'Avatar' => 'Аватар',
    'Avatar deleted' => 'Аватар видалений',
    'Avatar for ' => 'Аватар для ',
    'Blocked' => 'Заблокований',
    'Change password' => 'Змінити пароль',
    'Check your email for further instructions.' => 'Інструкції були відправлені на вашу пошту',
    'Click remove button below to remove this image' => 'Натисніть кнопку Видалити для видалення малюнка',
    'Create' => 'Створити',
    'Create User' => 'Створити користувача',
    'Current password' => 'Поточний пароль',
    'Delete' => 'Видалити',
    'Email' => 'Електронна пошта',
    'First Name' => 'Ім`я',
    'Follow the link below to reset your password:' => 'Для зміни пароля перейдіть за посиланням:',
    'Full Name' => 'Повне ім`я',
    'Hello {username}' => 'Привіт {username}',
    'Incorrect username or password.' => 'Невірний логін або пароль.',
    'Last Name' => 'Прізвище',
    'Login' => 'Авторизація',
    'New password' => 'Новий пароль',
    'New password was saved.' => 'Новий пароль збережений',
    'No avatar yet' => 'Аватар відсутній',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Відновлення паролю для аккаунту {name}',
    'Please choose your new password' => 'Введіть новий пароль',
    'Please fill out the following fields to login' => 'Для входу на сайт заповніть поля від вашого профілю',
    'Please fill out the following fields to signup' => 'Для реєстрації заповніть поля нижче',
    'Please fill out your email. A link to reset password will be sent there.' => 'Введіть пошту і ми відправимо інструкції по відновленню пароля.',
    'Profile' => 'Профіль',
    'Registration Date' => 'Дата реєстрації',
    'Remember me' => 'Запам`ятати мене',
    'Remove avatar' => 'Видалити аватар',
    'Repeat new password' => 'Повторіть пароль',
    'Request password reset' => 'Відновлення паролю',
    'Reset' => 'Очистити',
    'Reset password' => 'Відновити пароль',
    'Role' => 'Роль',
    'Save' => 'Зберегти',
    'Search' => 'Пошук',
    'Select status' => 'Виберіть статус',
    'Send' => 'Відправити',
    'Signup' => 'Реєстрація',
    'Sorry, we are unable to reset password for email provided.' => 'Неможливо відновити пароль для вказаної адреси.',
    'Status' => 'Статус',
    'Thanks! Your account was created successfully.' => 'Дякуємо! Ваш аккаунт був успішно створений.',
    'There is no user with this email address.' => 'Користувач з такою адресою не знайдений.',
    'This Email already exists.' => 'Такий Email вже зареєстрований',
    'This username already exists.' => 'Таке Ім`я користувача вже зареєстроване',
    'Update' => 'Оновити',
    'Update {modelClass}: ' => 'Оновити {modelClass}: ',
    'Upload your avatar by selecting browse below' => 'Виберіть аватар',
    'User has been created' => 'Користувач створений',
    'Username' => 'Логін',
    'Users' => 'Користувачі',
    'Waits of verify' => 'Очікує підтвердження',
    'Your passwords is changed.' => 'Пароль успішно змінено',
    'Your profile is blocked.' => 'Ваш аккаунт заблокований.',
    'Your profile is not confirmed.' => 'Ваш аккаунт не підтверджений.',
];
