<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Check your email for further instructions.' => '',
    'Follow the link below to reset your password:' => '',
    'Full Name' => '',
    'Please fill out the following fields to login' => '',
    'Please fill out the following fields to signup' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Registration Date' => 'Дата реєстрації',
    'Request password reset' => 'Відновлення паролю',
    'Sorry, we are unable to reset password for email provided.' => '',
    'There is no user with this email address.' => '',
    'User role have been updated' => '',
    'You can not block your own account' => '',
    'You can not change your own role' => '',
    'Please fill out the following fields to login:' => '@@@@',
    'Please fill out the following fields to signup:' => '@@@@',
    'Account details have been updated' => 'Деталі аккаунту оновлені',
    'Active' => 'Активний',
    'Avatar' => 'Аватар',
    'Avatar deleted' => 'Аватар видалений',
    'Blocked' => 'Заблокований',
    'Email' => 'Електронна пошта',
    'First Name' => 'Ім`я',
    'Hello {username}' => 'Привіт {username}',
    'Incorrect username or password.' => 'Невірний логін або пароль.',
    'Last Name' => 'Прізвище',
    'Login' => 'Авторизація',
    'New password was saved.' => 'Новий пароль збережений',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Відновлення паролю для аккаунту {name}',
    'Please choose your new password' => 'Введіть новий пароль',
    'Remember me' => 'Запам`ятати мене',
    'Reset password' => 'Відновити пароль',
    'Role' => 'Роль',
    'Save' => 'Зберегти',
    'Send' => 'Відправити',
    'Signup' => 'Реєстрація',
    'Status' => 'Статус',
    'This Email already exists.' => 'Такий Email вже зареєстрований',
    'This username already exists.' => 'Таке Ім`я користувача вже зареєстроване',
    'User has been blocked' => 'Користувач заблокований',
    'User has been created' => 'Користувач створений',
    'User has been unblocked' => 'Користувач розблокований',
    'Username' => 'Логін',
    'Waits of verify' => 'Очікує підтвердження',
    'Your profile is blocked.' => 'Ваш аккаунт заблокований.',
    'Your profile is not confirmed.' => 'Ваш аккаунт не підтверджений.',
];
