<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account details have been updated' => '',
    'Active' => '',
    'Avatar' => '',
    'Avatar deleted' => '',
    'Blocked' => '',
    'Check your email for further instructions.' => '',
    'Email' => '',
    'First Name' => '',
    'Follow the link below to reset your password:' => '',
    'Full Name' => '',
    'Hello {username}' => '',
    'Incorrect username or password.' => '',
    'Last Name' => '',
    'Login' => '',
    'New password was saved.' => '',
    'Password' => '',
    'Password reset for {name}' => '',
    'Please choose your new password' => '',
    'Please fill out the following fields to login' => '',
    'Please fill out the following fields to signup' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Registration Time' => '',
    'Remember me' => '',
    'Request password reset' => '',
    'Reset password' => '',
    'Role' => '',
    'Save' => '',
    'Send' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Status' => '',
    'There is no user with this email address.' => '',
    'This Email already exists.' => '',
    'This username already exists.' => '',
    'User has been blocked' => '',
    'User has been created' => '',
    'User has been unblocked' => '',
    'User role have been updated' => '',
    'Username' => '',
    'Waits of verify' => '',
    'You can not block your own account' => '',
    'You can not change your own role' => '',
    'Your profile is blocked.' => '',
    'Your profile is not confirmed.' => '',
    'Please choose your new password:' => '@@@@',
    'Please fill out the following fields to login:' => '@@@@',
    'Please fill out the following fields to signup:' => '@@@@',
];
