<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account details have been updated' => '',
    'Active' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar' => '',
    'Avatar deleted' => '',
    'Avatar for ' => '',
    'Blocked' => '',
    'Change password' => '',
    'Check your email for further instructions.' => '',
    'Click remove button below to remove this image' => '',
    'Create' => '',
    'Create User' => '',
    'Current password' => '',
    'Delete' => '',
    'Email' => '',
    'First Name' => '',
    'Follow the link below to reset your password:' => '',
    'Full Name' => '',
    'Hello {username}' => '',
    'Incorrect username or password.' => '',
    'Last Name' => '',
    'Login' => '',
    'New password' => '',
    'New password was saved.' => '',
    'No avatar yet' => '',
    'Password' => '',
    'Password change' => '',
    'Password reset for {name}' => '',
    'Please choose your new password' => '',
    'Please fill out the following fields to login' => '',
    'Please fill out the following fields to signup' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Profile' => '',
    'Registration Date' => '',
    'Remember me' => '',
    'Remove avatar' => '',
    'Repeat new password' => '',
    'Request password reset' => '',
    'Reset' => '',
    'Reset password' => '',
    'Role' => '',
    'Save' => '',
    'Search' => '',
    'Select status' => '',
    'Send' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Status' => '',
    'Thanks! Your account was created successfully.' => '',
    'There is no user with this email address.' => '',
    'This Email already exists.' => '',
    'This username already exists.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Upload your avatar by selecting browse below' => '',
    'User has been created' => '',
    'Username' => '',
    'Users' => '',
    'Waits of verify' => '',
    'Wrong current password.' => '',
    'Your passwords is changed.' => '',
    'Your profile is blocked.' => '',
    'Your profile is not confirmed.' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
];
